CREATE DATABASE `TC` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `TC`;

-- 1. EMPRESA
CREATE TABLE `EMPRESA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` varchar(255) NOT NULL,
  `NOME_FANTASIA` varchar(255) NOT NULL,
  `CNPJ_CPF` varchar(20) NOT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 2. SETOR
CREATE TABLE `SETOR` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `EMPRESA_ID` int NOT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  CONSTRAINT `SETOR_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 3. FUNCAO
CREATE TABLE `FUNCAO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `SETOR_ID` int NOT NULL,
  `EMPRESA_ID` int NOT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  KEY `SETOR_ID` (`SETOR_ID`),
  CONSTRAINT `FUNCAO_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`),
  CONSTRAINT `FUNCAO_ibfk_2` FOREIGN KEY (`SETOR_ID`) REFERENCES `SETOR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 4. USUARIOS
CREATE TABLE `USUARIOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `USUARIO` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `DATA_CADASTRO` date DEFAULT (curdate()),
  `HORA_CADASTRO` time DEFAULT (curtime()),
  `IS_DELETED` tinyint(1) DEFAULT '0',
  `EMPRESA_ID` int NOT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  CONSTRAINT `USUARIOS_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 5. PERMISSOES
CREATE TABLE `PERMISSOES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME_PERMISSAO` varchar(100) NOT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  UNIQUE KEY `NOME` (`NOME_PERMISSAO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 6. USUARIO_PERMISSAO
CREATE TABLE `USUARIO_PERMISSAO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `PERMISSAO_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`),
  KEY `PERMISSAO_ID` (`PERMISSAO_ID`),
  CONSTRAINT `USUARIO_PERMISSAO_ibfk_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIOS` (`ID`),
  CONSTRAINT `USUARIO_PERMISSAO_ibfk_2` FOREIGN KEY (`PERMISSAO_ID`) REFERENCES `PERMISSOES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 7. TIPO_DOCUMENTO
CREATE TABLE `TIPO_DOCUMENTO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME` (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 8. EPI
CREATE TABLE `EPI` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) NOT NULL,
  `DESCRICAO` varchar(255) NOT NULL,
  `CA` varchar(30) NOT NULL,
  `VALIDADE_EPI` date NOT NULL,
  `HORA_CADASTRO` time DEFAULT (curtime()),
  `DATA_CADASTRO` date DEFAULT (curdate()),
  `USUARIO_CADASTRO` int NOT NULL,
  `USUARIO_ALTERACAO` int NOT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `EPI_ibfk_1` FOREIGN KEY (`USUARIO_CADASTRO`) REFERENCES `USUARIOS` (`ID`),
  CONSTRAINT `EPI_ibfk_2` FOREIGN KEY (`USUARIO_ALTERACAO`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 9. OBRA
CREATE TABLE `OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME_OBRA` varchar(255) NOT NULL,
  `ENDERECO` varchar(255) NOT NULL,
  `EMPRESA_ID` int NOT NULL,
  `PAUSA` tinyint NOT NULL DEFAULT '0',
  `FINALIZADO` tinyint NOT NULL DEFAULT '0',
  `DATA_INICIO` date DEFAULT NULL,
  `DATA_FIM` date DEFAULT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `OBRA_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 10. FUNCIONARIOS
CREATE TABLE `FUNCIONARIOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `CPF` varchar(30) NOT NULL,
  `PIS` varchar(15) NOT NULL,
  `DATA_ADMISSAO` date NOT NULL,
  `DATA_DEMISSAO` date DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT (curdate()),
  `IS_DELETED` tinyint(1) DEFAULT '0',
  `EMPRESA_ID` int NOT NULL,
  `FUNCAO_ID` int NOT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `FUNCIONARIOS_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`),
  CONSTRAINT `FUNCIONARIOS_ibfk_2` FOREIGN KEY (`FUNCAO_ID`) REFERENCES `FUNCAO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 11. FUNCIONARIO_EPI
CREATE TABLE `FUNCIONARIO_EPI` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_ID` int NOT NULL,
  `EPI_ID` int NOT NULL,
  `QUANTIDADE` int DEFAULT '1',
  `DATA_ENTREGA` date NOT NULL,
  `DATA_DEVOLUCAO` date DEFAULT NULL,
  `RESPONSAVEL_ENTREGA` int NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FUNCIONARIO_EPI_ibfk_1` FOREIGN KEY (`FUNCIONARIO_ID`) REFERENCES `FUNCIONARIOS` (`ID`),
  CONSTRAINT `FUNCIONARIO_EPI_ibfk_2` FOREIGN KEY (`EPI_ID`) REFERENCES `EPI` (`ID`),
  CONSTRAINT `FUNCIONARIO_EPI_ibfk_3` FOREIGN KEY (`RESPONSAVEL_ENTREGA`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 12. FUNCIONARIO_OBRA
CREATE TABLE `FUNCIONARIO_OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_ID` int NOT NULL,
  `OBRA_ID` int NOT NULL,
  `DATA_INICIO` date DEFAULT NULL,
  `DATA_FIM` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FUNCIONARIO_OBRA_ibfk_1` FOREIGN KEY (`FUNCIONARIO_ID`) REFERENCES `FUNCIONARIOS` (`ID`),
  CONSTRAINT `FUNCIONARIO_OBRA_ibfk_2` FOREIGN KEY (`OBRA_ID`) REFERENCES `OBRA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 13. TREINAMENTOS
CREATE TABLE `TREINAMENTOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) NOT NULL,
  `DESCRICAO` varchar(500) DEFAULT NULL,
  `NR_REFERENCIA` varchar(50) NOT NULL,
  `CARGA_HORARIA` int DEFAULT NULL,
  `VALIDADE_MESES` int DEFAULT NULL,
  `EMPRESA_ID` int NOT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `TREINAMENTOS_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 14. FUNCIONARIO_TREINAMENTO
CREATE TABLE `FUNCIONARIO_TREINAMENTO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_ID` int NOT NULL,
  `TREINAMENTO_ID` int NOT NULL,
  `DATA_REALIZACAO` date NOT NULL,
  `DATA_VALIDADE` date DEFAULT NULL,
  `CERTIFICADO` varchar(255) DEFAULT NULL,
  `RESPONSAVEL` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FUNCIONARIO_TREINAMENTO_ibfk_1` FOREIGN KEY (`FUNCIONARIO_ID`) REFERENCES `FUNCIONARIOS` (`ID`),
  CONSTRAINT `FUNCIONARIO_TREINAMENTO_ibfk_2` FOREIGN KEY (`TREINAMENTO_ID`) REFERENCES `TREINAMENTOS` (`ID`),
  CONSTRAINT `FUNCIONARIO_TREINAMENTO_ibfk_3` FOREIGN KEY (`RESPONSAVEL`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 15. DOCUMENTACAO_EMPRESA
CREATE TABLE `DOCUMENTACAO_EMPRESA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DATA_UPLOAD` date DEFAULT (curdate()),
  `EMPRESA_ID` int NOT NULL,
  `TIPO_DOCUMENTO_ID` int NOT NULL,
  `NOME_ARQUIVO` varchar(255) NOT NULL,
  `CAMINHO` varchar(500) NOT NULL,
  `DESCRICAO` varchar(500) DEFAULT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `DOC_EMPRESA_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`),
  CONSTRAINT `DOC_EMPRESA_ibfk_2` FOREIGN KEY (`TIPO_DOCUMENTO_ID`) REFERENCES `TIPO_DOCUMENTO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 16. DOCUMENTACAO_FUNCIONARIO
CREATE TABLE `DOCUMENTACAO_FUNCIONARIO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_ID` int NOT NULL,
  `TIPO_DOCUMENTO_ID` int NOT NULL,
  `NOME_ARQUIVO` varchar(255) NOT NULL,
  `CAMINHO` varchar(500) NOT NULL,
  `DESCRICAO` varchar(500) DEFAULT NULL,
  `DATA_UPLOAD` datetime DEFAULT CURRENT_TIMESTAMP,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `DOC_FUNCIONARIO_ibfk_1` FOREIGN KEY (`FUNCIONARIO_ID`) REFERENCES `FUNCIONARIOS` (`ID`),
  CONSTRAINT `DOC_FUNCIONARIO_ibfk_2` FOREIGN KEY (`TIPO_DOCUMENTO_ID`) REFERENCES `TIPO_DOCUMENTO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 17. DOCUMENTACAO_OBRA
CREATE TABLE `DOCUMENTACAO_OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `OBRA_ID` int NOT NULL,
  `TIPO_DOCUMENTO_ID` int NOT NULL,
  `NOME_ARQUIVO` varchar(255) NOT NULL,
  `CAMINHO` varchar(500) NOT NULL,
  `DESCRICAO` varchar(500) DEFAULT NULL,
  `DATA_UPLOAD` date DEFAULT NULL,
  `PUBLIC_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PUBLIC_ID` (`PUBLIC_ID`),
  CONSTRAINT `DOC_OBRA_ibfk_1` FOREIGN KEY (`OBRA_ID`) REFERENCES `OBRA` (`ID`),
  CONSTRAINT `DOC_OBRA_ibfk_2` FOREIGN KEY (`TIPO_DOCUMENTO_ID`) REFERENCES `TIPO_DOCUMENTO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
