CREATE DATABASE `TC`;
USE `TC`;

-- =========================
-- EMPRESA
-- =========================
CREATE TABLE `EMPRESA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` varchar(255) NOT NULL,
  `NOME_FANTASIA` varchar(255) NOT NULL,
  `CNPJ_CPF` varchar(20) NOT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- OBRAS
-- =========================
CREATE TABLE `OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME_OBRA` varchar(255) NOT NULL,
  `EMPRESA_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  CONSTRAINT `OBRA_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- USUÁRIOS
-- =========================
CREATE TABLE `USUARIOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `USUARIO` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `DATA_CADASTRO` date DEFAULT (curdate()),
  `HORA_CADASTRO` time DEFAULT (curtime()),
  `IS_DELETED` tinyint(1) DEFAULT '0',
  `EMPRESA_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  CONSTRAINT `USUARIOS_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- PERMISSÕES
-- =========================
CREATE TABLE `PERMISSOES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME` (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- RELAÇÃO USUÁRIOS <-> PERMISSÕES
-- =========================
CREATE TABLE `USUARIO_PERMISSAO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `PERMISSAO_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USUARIO_ID` (`USUARIO_ID`),
  KEY `PERMISSAO_ID` (`PERMISSAO_ID`),
  CONSTRAINT `USUARIO_PERMISSAO_ibfk_1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIOS` (`ID`),
  CONSTRAINT `USUARIO_PERMISSAO_ibfk_2` FOREIGN KEY (`PERMISSAO_ID`) REFERENCES `PERMISSOES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- SETORES
-- =========================
CREATE TABLE `SETOR` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `EMPRESA_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  CONSTRAINT `SETOR_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- FUNÇÕES
-- =========================
CREATE TABLE `FUNCAO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `SETOR_ID` int NOT NULL,
  `EMPRESA_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  KEY `SETOR_ID` (`SETOR_ID`),
  CONSTRAINT `FUNCAO_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`),
  CONSTRAINT `FUNCAO_ibfk_2` FOREIGN KEY (`SETOR_ID`) REFERENCES `SETOR` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- FUNCIONÁRIOS
-- =========================
CREATE TABLE `FUNCIONARIOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `CPF` varchar(30) NOT NULL,
  `DATA_ADMISSAO` date NOT NULL,
  `DATA_DEMISSAO` date DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT (curdate()),
  `IS_DELETED` tinyint(1) DEFAULT '0',
  `EMPRESA_ID` int NOT NULL,
  `FUNCAO_ID` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `EMPRESA_ID` (`EMPRESA_ID`),
  KEY `FUNCAO_ID` (`FUNCAO_ID`),
  CONSTRAINT `FUNCIONARIOS_ibfk_1` FOREIGN KEY (`EMPRESA_ID`) REFERENCES `EMPRESA` (`ID`),
  CONSTRAINT `FUNCIONARIOS_ibfk_2` FOREIGN KEY (`FUNCAO_ID`) REFERENCES `FUNCAO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- RELAÇÃO FUNCIONÁRIOS <-> OBRAS
-- =========================
CREATE TABLE `FUNCIONARIO_OBRA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_ID` int NOT NULL,
  `OBRA_ID` int NOT NULL,
  `DATA_INICIO` date DEFAULT NULL,
  `DATA_FIM` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FUNCIONARIO_ID` (`FUNCIONARIO_ID`),
  KEY `OBRA_ID` (`OBRA_ID`),
  CONSTRAINT `FUNCIONARIO_OBRA_ibfk_1` FOREIGN KEY (`FUNCIONARIO_ID`) REFERENCES `FUNCIONARIOS` (`ID`),
  CONSTRAINT `FUNCIONARIO_OBRA_ibfk_2` FOREIGN KEY (`OBRA_ID`) REFERENCES `OBRA` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- EPIs
-- =========================
CREATE TABLE `EPI` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) NOT NULL,
  `DESCRICAO` varchar(255) NOT NULL,
  `CA` varchar(30) NOT NULL,
  `VALIDADE_EPI` date NOT NULL,
  `HORA_CADASTRO` time DEFAULT (curtime()),
  `DATA_CADASTRO` date DEFAULT (curdate()),
  `USUARIO_CADASTRO` int NOT NULL,
  `USUARIO_ALTERACAO` int NOT NULL,
  `IS_DELETED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `USUARIO_CADASTRO` (`USUARIO_CADASTRO`),
  KEY `USUARIO_ALTERACAO` (`USUARIO_ALTERACAO`),
  CONSTRAINT `EPI_ibfk_1` FOREIGN KEY (`USUARIO_CADASTRO`) REFERENCES `USUARIOS` (`ID`),
  CONSTRAINT `EPI_ibfk_2` FOREIGN KEY (`USUARIO_ALTERACAO`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================
-- ENTREGAS DE EPIs PARA FUNCIONARIOS
-- =========================
CREATE TABLE `FUNCIONARIO_EPI` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FUNCIONARIO_ID` int NOT NULL,
  `EPI_ID` int NOT NULL,
  `QUANTIDADE` int DEFAULT 1,
  `DATA_ENTREGA` date NOT NULL,
  `DATA_DEVOLUCAO` date DEFAULT NULL,
  `RESPONSAVEL_ENTREGA` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FUNCIONARIO_ID` (`FUNCIONARIO_ID`),
  KEY `EPI_ID` (`EPI_ID`),
  KEY `RESPONSAVEL_ENTREGA` (`RESPONSAVEL_ENTREGA`),
  CONSTRAINT `FUNCIONARIO_EPI_ibfk_1` FOREIGN KEY (`FUNCIONARIO_ID`) REFERENCES `FUNCIONARIOS` (`ID`),
  CONSTRAINT `FUNCIONARIO_EPI_ibfk_2` FOREIGN KEY (`EPI_ID`) REFERENCES `EPI` (`ID`),
  CONSTRAINT `FUNCIONARIO_EPI_ibfk_3` FOREIGN KEY (`RESPONSAVEL_ENTREGA`) REFERENCES `USUARIOS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;