CREATE TABLE EMPRESA(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    NOME_FANTASIA VARCHAR(255) NOT NULL,
    CNPJ_CPF VARCHAR(20) NOT NULL,
    IS_DELETED BOOLEAN DEFAULT false
);

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DATA_CADASTRO DATE DEFAULT (CURRENT_DATE()),
    HORA_CADASTRO TIME DEFAULT (CURRENT_TIME()),
    ROSFIELD_CONTROLE BOOLEAN DEFAULT false,
    ROSFIELD_FINANCEIRO BOOLEAN DEFAULT false,
    ROSFIELD_ADMIN BOOLEAN DEFAULT false,
    IS_DELETED BOOLEAN DEFAULT false,
    EMPRESA_ID INT NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE SETOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMPRESA_ID INT NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE FUNCAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SETOR_ID INT NOT NULL,
    EMPRESA_ID INT NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
    FOREIGN KEY (SETOR_ID) REFERENCES SETOR(ID)
);

CREATE TABLE FUNCIONARIOS (
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    DATA_DEMISSAO DATE,
    DATA_CADASTRO DATE DEFAULT (CURRENT_DATE()),
    IS_DELETED BOOLEAN DEFAULT false,
    EMPRESA_ID INT NOT NULL,
    FUNCAO_ID INT NOT NULL,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
    FOREIGN KEY (FUNCAO_ID) REFERENCES FUNCAO(ID)
);

CREATE TABLE EPI(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QUANT INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CA VARCHAR(30) NOT NULL,
    VALIDADE_EPI DATE NOT NULL,
    HORA_CADASTRO TIME DEFAULT (CURRENT_TIME()),
    DATA_CADASTRO DATE DEFAULT (CURRENT_DATE()),
    USUARIO_CADASTRO INT NOT NULL,
    USUARIO_ALTERACAO INT NOT NULL,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (USUARIO_CADASTRO) REFERENCES USUARIOS(ID),
    FOREIGN KEY (USUARIO_ALTERACAO) REFERENCES USUARIOS(ID)
);

CREATE TABLE DOCUMENTOS_EMPRESA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPRESA_ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    TIPO VARCHAR(100),
    DATA_EMISSAO DATE,
    DATA_VALIDADE DATE,
    ARQUIVO_PATH VARCHAR(500),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    DATA_CADASTRO DATE DEFAULT (CURRENT_DATE()),
    USUARIO_CADASTRO INT,
    FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
    FOREIGN KEY (USUARIO_CADASTRO) REFERENCES USUARIOS(ID)
);

CREATE TABLE DOCUMENTOS_FUNCIONARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FUNCIONARIO_ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    TIPO VARCHAR(100),.
    DATA_EMISSAO DATE,
    DATA_VALIDADE DATE,
    ARQUIVO_PATH VARCHAR(500),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    DATA_CADASTRO DATE DEFAULT (CURRENT_DATE()),
    USUARIO_CADASTRO INT,
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(ID),
    FOREIGN KEY (USUARIO_CADASTRO) REFERENCES USUARIOS(ID)
);

CREATE TABLE ENTREGA_EPI (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FUNCIONARIO_ID INT NOT NULL,
    EPI_ID INT NOT NULL,
    QUANT INT NOT NULL,
    DATA_ENTREGA DATE NOT NULL DEFAULT (CURRENT_DATE),
    USUARIO_ENTREGA INT NOT NULL,
    -- usuário do sistema que registrou
    DATA_DEVOLUCAO DATE,
    OBSERVACAO VARCHAR(255),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS(ID),
    FOREIGN KEY (EPI_ID) REFERENCES EPI(ID),
    FOREIGN KEY (USUARIO_ENTREGA) REFERENCES USUARIOS(ID)
);